taichi-dev/taichi-aot-demo

implicit_fem/include/fem_app.h

Changes after https://github.com/taichi-dev/taichi/pull/4762

Match 4762

---

implicit_fem/include/fem_app.h

Changes that are affected by Taichi refactor: https://github.com/taichi-dev/taichi/pull/5058.

Update fem header path to use gfx runtime

---

implicit_fem/include/fem_app.h

It turns out the default behavior of map/unmap a device allocation
differs between desktop and mobile. (maybe due to unified memory on
mobile?) So let's use a staging buffer to correctly handle this.

[bug] Use staging buffer for host access in implicit_fem desktop demo

---

.gitignore
4_texture_fractal/CMakeLists.txt
4_texture_fractal/app.cpp
4_texture_fractal/assets/fractal.py
CMakeLists.txt
framework/include/taichi/aot_demo/draws/draw_texture.hpp
framework/include/taichi/aot_demo/framework.hpp
framework/include/taichi/aot_demo/graphics_runtime.hpp
framework/include/taichi/aot_demo/renderer.hpp
framework/src/taichi/aot_demo/draws/draw_texture.cpp
framework/src/taichi/aot_demo/renderer.cpp

This PR added support for texture draws.

Texture draw

---

.gitignore
0_tutorial_cgraph/CMakeLists.txt
0_tutorial_cgraph/app.cpp
0_tutorial_cgraph/assets/tutorial.py
0_tutorial_kernel/CMakeLists.txt
0_tutorial_kernel/app.cpp
0_tutorial_kernel/assets/tutorial.py
CMakeLists.txt

Already passed CI in https://github.com/taichi-dev/taichi/pull/6543 (already switched to master)
We'll need to merge this PR first and then #6543 to make sure CI stability.

[demo] Add code for AOT tutorial

---

1_hello_world/app.cpp
1_hello_world_with_interop/app.cpp
2_mpm88/app.cpp
3_implicit_fem/app.cpp
4_texture_fractal/app.cpp
5_sph/app.cpp
6_taichi_sparse/app.cpp
7_comet/app.cpp
framework/include/taichi/aot_demo/framework.hpp
framework/src/taichi/aot_demo/entry_points/glfw.cpp
framework/src/taichi/aot_demo/entry_points/headless.cpp
framework/src/taichi/aot_demo/framework.cpp

Test with: https://github.com/taichi-dev/taichi/pull/6544

[bug] Refactor global variable ti::aot_demo::Framework into local varriable

---

2_mpm88/assets/mpm88.py
framework/include/taichi/aot_demo/renderer.hpp
framework/src/taichi/aot_demo/renderer.cpp

This PR includes changes from @PENGUINLIONG and supersedes #55 due to mass refactor happened in master.
To see the printed values, try:
```
./build/headless/E2_mpm88_headless --debug
./build/glfw/E2_mpm88_glfw --debug
```

[vulkan] Enable printing in mpm88 example

---

5_sph/assets/sph.py

Test with: https://github.com/taichi-dev/taichi/pull/6654

Fix sph headless CI failure

---

0_tutorial_cgraph/CMakeLists.txt
0_tutorial_kernel/CMakeLists.txt
cmake/demo.cmake
cmake/env.cmake
framework/src/taichi/aot_demo/entry_points/android.cpp
framework/src/taichi/aot_demo/entry_points/android_impl.c

Tested with: https://github.com/taichi-dev/taichi/pull/6833

Android build infra (#85)

---

0_tutorial_cgraph/app.cpp
0_tutorial_kernel/app.cpp
framework/include/taichi/aot_demo/common.hpp
framework/src/taichi/aot_demo/interop/cross_device_copy.cpp
framework/src/taichi/aot_demo/interop/texture_utils.cpp

https://github.com/taichi-dev/taichi/pull/6955

Fixed compute graph tutorial demo

---

2_mpm88/assets/mpm88.py

https://github.com/taichi-dev/taichi/pull/6958

Remove allocations in MPM compiler script

---

scripts/build-android-app.sh
scripts/build-android.sh
scripts/build-taichi-android.sh

Tested with: https://github.com/taichi-dev/taichi/pull/6996

Fix build scripts for Android App

---

implicit_fem/include/fem_app.h

[#6954](https://github.com/taichi-dev/taichi/pull/6954/)

Update to new resource binding API

---

0_tutorial_cgraph/assets/tutorial.py
0_tutorial_kernel/assets/tutorial.py
2_mpm88/assets/mpm88.py
3_implicit_fem/assets/implicit_fem.py
4_texture_fractal/assets/fractal.py
5_sph/assets/sph.py
6_taichi_sparse/assets/taichi_sparse.py
7_comet/assets/comet.py
cmake/env.cmake
implicit_fem/python/implicit_fem.py
legacy_demos/nbody_ndarray/nbody.py
tutorial.md

https://github.com/taichi-dev/taichi/pull/7085

[misc] Remove unused filename in aot module save

---

6_taichi_sparse/assets/taichi_sparse.py

https://github.com/taichi-dev/taichi/pull/7098

Replace ti.Matrix.rotation2d with ti.math.rotation2d

---

cmake/demo.cmake

This is a potential fix for https://github.com/taichi-dev/taichi/issues/7070
Passed CI at https://github.com/taichi-dev/taichi/pull/7147

[build] Add dependency between custom commands to ensure execution order

---

4_texture_fractal/assets/fractal.py

https://github.com/taichi-dev/taichi/pull/7267

[misc] Remove usage of deprecated kwarg in rw_texture type annotation

---

.gitignore
0_tutorial_cgraph/CMakeLists.txt
0_tutorial_cgraph/app.cpp
0_tutorial_kernel/CMakeLists.txt
0_tutorial_kernel/app.cpp
2_mpm88/assets/mpm88.py
3_implicit_fem/assets/implicit_fem.py
CMakeLists.txt
cmake/FindTaichi.cmake
cmake/demo.cmake
cmake/env.cmake
framework/CMakeLists.txt
framework/include/taichi/aot_demo/common.hpp
scripts/build-taichi-android.sh

Checked with https://github.com/taichi-dev/taichi/pull/7297.
Fixed various issues in current implementation

Fixed AOT demo breakage

---

.gitmodules
external/CMakeLists.txt
framework/CMakeLists.txt
framework/src/taichi/aot_demo/glslang.cpp

Checked with https://github.com/taichi-dev/taichi/pull/7416.
Removed duplicate submodules in AOT demos. This should save some CI time.

Remove duplicate submodules

---

cmake/demo.cmake

According to
https://cmake.org/cmake/help/latest/command/add_custom_command.html, `add_custom_command` doesn't take `TARGET` and `DEPENDS` at the same time but cmake didn't complain, sigh...

[build] Fix dependency between aot file generation and copy

---

0_tutorial_cgraph/assets/tutorial.py
0_tutorial_kernel/assets/tutorial.py
2_mpm88/assets/mpm88.py
3_implicit_fem/assets/implicit_fem.py
5_sph/assets/sph.py
7_comet/assets/comet.py
implicit_fem/android/app/src/main/assets/shaders/aot/implicit_fem/metadata.json
legacy_demos/nbody_ndarray/java_runtime/NbodyNdarray.java
legacy_demos/nbody_ndarray/res/metadata.json
tutorial.md

Checked with https://github.com/taichi-dev/taichi/pull/7492

[misc] Replace field_dim with ndim

---

CMakeLists.txt
external/CMakeLists.txt
framework/CMakeLists.txt
framework/include/taichi/aot_demo/common.hpp
framework/src/taichi/aot_demo/glslang.cpp
framework/src/taichi/aot_demo/vmaimpl.cpp

Backref: https://github.com/taichi-dev/taichi/pull/7505

[build] Update dependencies

---

2_mpm88/assets/mpm88.py
5_sph/assets/sph.py
legacy_demos/nbody_ndarray/nbody.py

Testing in https://github.com/taichi-dev/taichi/pull/7941

Replace the usages of ti.any_arr to ti.types.ndarray
